Forcing lastet version of libxml2
Due to bug found in previous version

```Python
XMLSchemaParseError: local list type: A type, derived by list or union, must have the simple ur-type definition as base type, not '{http://www.opengis.net/gml}doubleOrNullList'
```